function getRandomGreeting() {
  var greetings = [
    "Bubber is the goat",
    "Beep boop! Are you a robot?",
    "jablicky asparagus timmypop",
    "How many sides does a circle have?",
    "You can read btw",
    "Made you look!",
    "Redbull gives you wings...",
    "Since 2020!",
    "As seen on TV!",
    "guess what! vvmvvh",
    "Cold as ice!",
    "Made in the US!",
    "Made by Bubber!",
    "Reload the page NOW!",
    "explicit goat videos",
    "Running Chimp.exe",
    "WARNING: You may lose your pocket chimp if you proceed!",
    "Do you bite your ice cream?",
    "#Relatable",
    "chinese grandpa vs the evil bees in the hibiscus",
    "You got games on your phone?",
    "Powered by hamsters!",
    "*insert cool explosion*",
    "Got to go fast!",
    "My iPad passcode is 563543 btw",
    "james the popsicle?!",
    "Sponsored by Honey!",
    "Sponsored by Chimp&co!",
    "la pa",
    "Powered by 128 Gigs of RAM!",
    "Powered by 16MB of RAM!",
    "I'm Slim Shady, yes, I'm the real Shady!",
    "paway in a horsi gcaa",
    " mike pig sexual assault allegations",
    "Everlong",
    "I'm gonna pop some gizzies",
    "Shoutout toe",
    "thx stackoverflow!",
    "are you a gamer?",
    "It is time to get funky!",
    "We didn't start the fire! It was always burning, since the world's been turning!",
    "Don't ask questions if you can't handle the answers!",
    "If you are using Microsoft Edge, you need some help.",
    "Vengeance is hereby mine",
    "Shoutout to Schlopis!",
    "Shoutout to PRG!",
    "Woo! /g/",
    "do mice like it when i laa.",
    "Is this the United Airlines costumer service center?",
    "POV that one person who's 2 braincells are fighting for second place.",
    "bottom text",
    "buzzy bee disposal center",
    "No fun allowed",
    "henry licks a poo",
    "i do love buying pringle guzzies",
    "'If you are trash go play Fortnite you loser' - Sun Tzu, Art of war",
    "no matter what you say I DONT HAVE HORSES",
    "WHERES MY V-BUCKS MOM >:(",
    "Avocados \ud83e\udd51 from Mexico \ud83c\uddf2\ud83c\uddfd",
    "reload for another message",
    "hi graggle",
    "i just splatooned on my dog!",
    "And just to think I knew him before he was famous",
    "Trust me, I did not copy Minecraft with this",
    "It is everyday bro",
    "That proves you are unusual",
    "What's my age again?",
    "This is the 5th time this week, and it's only Monday",
    "You bum",
    "poodlepoop!",
    "Toss the Turtle is pretty fun",
    "i put coins in my special place",
    "The skeleton with the sword. HE FOUND YOU!",
    "I spent too much time making these",
  ];
  var randomIndex = Math.floor(Math.random() * greetings.length);
  return greetings[randomIndex];
}

document.getElementById("subtitle").innerText = getRandomGreeting();
